'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'Type created for JSON at <<root>>
Partial Public Class RootClass

    '結果
    Public api_result As Integer

    '結果のメッセージ
    '例：成功
    Public api_result_msg As String

    'APIのデータ
    Public api_data As Api_data
End Class

'Type created for JSON at <<root>> --> api_data
Partial Public Class Api_data

    '現在の所有資材・資源についてのデータ
    Public api_material() As Api_material

    '現在の艦隊についてのデータ
    Public api_deck_port() As Api_deck_port

    '現在の入渠ドックについてのデータ
    Public api_ndock() As Api_ndock

    '所有艦娘についてのデータ
    Public api_ship() As Api_ship

    '提督についてのデータ
    Public api_basic As Api_basic

    '母港画面の履歴に関するデータ
    Public api_log() As Api_log

    '母港で流れるBGMの番号
    Public api_p_bgm_id As Integer

    '同時に実行できる任務数
    Public api_parallel_quest_count As Integer
End Class

'Type created for JSON at <<root>> --> api_data --> api_material
Partial Public Class Api_material

    '固有のデータ？
    Public api_member_id As Integer

    '資材・資源の区別をする値
    '値一覧
    '1:燃料
    '2:弾薬
    '3:鋼材
    '4:ボーキサイト
    '5:高速建造材
    '6:高速修復材
    '7:開発資材
    '8:改修資材
    Public api_id As Integer

    '↑上の資材・資源の数値
    Public api_value As Integer
End Class

'Type created for JSON at <<root>> --> api_data --> api_deck_port
Partial Public Class Api_deck_port

    '固有のデータ？
    Public api_member_id As Integer

    '内部的な艦隊の番号
    '1～4まで存在する
    Public api_id As Integer

    '艦隊の名前
    '最大半角12文字
    Public api_name As String

    'よくわからないやつ
    Public api_name_id As String

    '遠征情報
    Public api_mission() As Long

    '旗艦？
    Public api_flagship As String

    '所属艦娘の情報
    Public api_ship() As Double
End Class

'Type created for JSON at <<root>> --> api_data --> api_ndock
Partial Public Class Api_ndock

    '固有のデータ？
    Public api_member_id As Integer

    '入渠ドックの番号
    '1～4
    Public api_id As Integer

    '入渠ドックの状況
    '-1:未開放
    '0:Empty
    'これより後は未調査
    Public api_state As Double

    '入渠中の艦娘ID
    Public api_ship_id As Integer

    '未調査
    Public api_complete_time As Integer

    '未調査
    Public api_complete_time_str As String

    '未調査
    Public api_item1 As Integer

    '未調査
    Public api_item2 As Integer

    '未調査
    Public api_item3 As Integer

    '未調査
    Public api_item4 As Integer
End Class

'Type created for JSON at <<root>> --> api_data --> api_ship
Partial Public Class Api_ship

    '艦娘ID
    'このIDは入手順に入る
    Public api_id As Integer

    '図鑑番号
    Public api_sortno As Integer

    'API独自の判別番号
    'グラフィックとかの判別に使う
    Public api_ship_id As Integer

    'Lv
    Public api_lv As Integer

    '経験値関係
    Public api_exp() As Integer

    '現在のHP
    Public api_nowhp As Integer

    '最大HP
    Public api_maxhp As Integer

    '速度？
    Public api_soku As Integer

    '未調査
    Public api_leng As Integer

    '現在所持している装備について
    Public api_slot() As Double

    'よくわからないやつ
    Public api_onslot() As Integer

    'よくわからないやつ
    Public api_slot_ex As Double

    'よくわからないやつ
    Public api_kyouka() As Integer

    'よくわからないやつ
    Public api_backs As Integer

    '燃料の量
    Public api_fuel As Integer

    '弾薬の量
    Public api_bull As Integer

    'スロット数？
    Public api_slotnum As Integer

    '入渠時間(ms)
    Public api_ndock_time As Integer

    'よくわからないやつ
    Public api_ndock_item() As Integer

    'よくわからないやつ
    Public api_srate As Integer

    'cond値
    Public api_cond As Integer

    '火力についてのデータ
    Public api_karyoku() As Integer

    '雷装についてのデータ
    Public api_raisou() As Integer

    '対空についてのデータ
    Public api_taiku() As Integer

    '装甲についてのデータ
    Public api_soukou() As Integer

    '回避についてのデータ
    Public api_kaihi() As Integer

    '対潜についてのデータ
    Public api_taisen() As Integer

    '索敵についてのデータ
    Public api_sakuteki() As Integer

    '運についてのデータ
    Public api_lucky() As Integer

    'ロック状態
    Public api_locked As Integer

    'ロックされた装備の有無
    Public api_locked_equip As Integer
End Class

'Type created for JSON at <<root>> --> api_data --> api_basic
Partial Public Class Api_basic

    '固有のデータ？
    Public api_member_id As String

    '提督の名前
    Public api_nickname As String

    'よくわからないやつ
    Public api_nickname_id As String

    'よくわからないやつ
    Public api_active_flag As Integer

    'おそらくログイン日時
    Public api_starttime As Long

    '提督Lv
    Public api_level As Integer

    '提督のランク
    Public api_rank As Integer

    '提督経験値
    Public api_experience As Integer

    'よくわからないやつ
    Public api_fleetname As Object

    '演習のときに出るあのコメント
    Public api_comment As String

    'よくわからないやつ
    Public api_comment_id As String

    '最大所持艦娘数
    Public api_max_chara As Integer

    '最大所持装備数
    Public api_max_slotitem As Integer

    'よくわからないやつ
    Public api_max_kagu As Integer

    'よくわからないやつ
    Public api_playtime As Integer

    'たぶんチュートリアル中かどうかの判別用
    Public api_tutorial As Integer

    '現在の家具データ
    Public api_furniture() As Integer

    'よくわからないやつ
    Public api_count_deck As Integer

    '初期ドック数？
    Public api_count_kdock As Integer

    '現在のドック数？
    Public api_count_ndock As Integer

    '家具コイン数
    Public api_fcoin As Integer

    '出撃の勝数
    Public api_st_win As Integer

    '出撃の敗数
    Public api_st_lose As Integer

    '遠征の回数
    Public api_ms_count As Integer

    '遠征の成功数
    Public api_ms_success As Integer

    '演習の勝数
    Public api_pt_win As Integer

    '演習の敗数
    Public api_pt_lose As Integer

    'よくわからないやつ
    Public api_pt_challenged As Integer

    'よくわからないやつ
    Public api_pt_challenged_win As Integer

    'よくわからないやつ
    Public api_firstflag As Integer

    'チュートリアル進行度
    Public api_tutorial_progress As Integer

    'よくわからないやつ
    Public api_pvp() As Integer

    'たぶん甲勲章の数
    Public api_medals As Integer

    'よくわからないやつ
    Public api_large_dock As Integer
End Class

'Type created for JSON at <<root>> --> api_data --> api_log
Partial Public Class Api_log

    'ログ番号
    Public api_no As Integer

    'ログの種別
    Public api_type As String

    'ログの状態？
    Public api_state As String

    'ログに表示されるメッセージ
    Public api_message As String
End Class
Public Class 艦これ構造体定義

End Class
